[project]
name = "30min-of-deep-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "appnope==0.1.3",
    "asttokens==2.0.5",
    "bottleneck==1.4.2",
    "brotli==1.0.9",
    "comm==0.2.1",
    "contourpy==1.3.1",
    "cycler==0.11.0",
    "debugpy==1.8.11",
    "decorator==5.1.1",
    "deprecated==1.2.13",
    "executing==0.8.3",
    "filelock==3.13.1",
    "fonttools==4.55.3",
    "fsspec==2024.12.0",
    "gmpy2==2.2.1",
    "importlib-metadata==8.5.0",
    "ipykernel==6.29.5",
    "ipython==8.30.0",
    "jedi==0.19.2",
    "jinja2==3.1.6",
    "jupyter-client==8.6.3",
    "jupyter-core==5.7.2",
    "kiwisolver==1.4.8",
    "markupsafe==3.0.2",
    "matplotlib==3.10.0",
    "matplotlib-inline==0.1.6",
    "mpmath==1.3.0",
    "nest-asyncio==1.6.0",
    "networkx==3.4.2",
    "numpy==2.2.4",
    "opentelemetry-api==1.30.0",
    "packaging==24.2",
    "pandas==2.2.3",
    "parso==0.8.4",
    "pexpect==4.8.0",
    "pillow==11.1.0",
    "pip==25.0",
    "platformdirs==3.10.0",
    "prompt-toolkit==3.0.43",
    "psutil==5.9.0",
    "ptyprocess==0.7.0",
    "pure-eval==0.2.2",
    "pygments==2.15.1",
    "pyparsing==3.2.0",
    "python-dateutil==2.9.0.post0",
    "pytz==2024.1",
    "pyzmq==26.2.0",
    "setuptools==72.1.0",
    "six==1.16.0",
    "stack-data==0.2.0",
    "sympy==1.13.1",
    "tornado==6.4.2",
    "traitlets==5.14.3",
    "typing-extensions==4.12.2",
    "tzdata==2023.3",
    "wcwidth==0.2.5",
    "wheel==0.45.1",
    "wrapt==1.17.0",
    "zipp==3.21.0",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
    "scikit-learn>=1.6.1",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
    { index = "pytorch-cu124", marker = "sys_platform == 'linux'" },
]
torchvision = [
    { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
    { index = "pytorch-cu124", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true


[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "nbdime>=4.0.2",
    "nbqa>=1.9.1",
    "pre-commit>=4.2.0",
    "ruff>=0.11.5",
]
