[project]
name = "30min-of-deep-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anyio==4.9.0",
    "appnope==0.1.3",
    "argon2-cffi==23.1.0",
    "argon2-cffi-bindings==21.2.0",
    "arrow==1.3.0",
    "asttokens==2.0.5",
    "attrs==25.3.0",
    "autopep8==2.3.2",
    "beautifulsoup4==4.13.3",
    "bleach==6.2.0",
    "bottleneck==1.4.2",
    "cached-property==1.5.2",
    "certifi==2025.1.31",
    "cffi==1.17.1",
    "cfgv==3.3.1",
    "charset-normalizer==3.4.1",
    "colorama==0.4.6",
    "comm==0.2.1",
    "contourpy==1.3.1",
    "cycler==0.11.0",
    "debugpy==1.8.11",
    "decorator==5.1.1",
    "defusedxml==0.7.1",
    "deprecated==1.2.13",
    "distlib==0.3.9",
    "exceptiongroup==1.2.2",
    "executing==0.8.3",
    "filelock==3.13.1",
    "fonttools==4.55.3",
    "fqdn==1.5.1",
    "fsspec==2024.12.0",
    "gitdb==4.0.12",
    "gitpython==3.1.44",
    "gmpy2==2.2.1",
    "h2==4.2.0",
    "hpack==4.1.0",
    "hyperframe==6.1.0",
    "identify==2.6.9",
    "idna==3.10",
    "importlib-metadata==8.5.0",
    "importlib-resources==6.5.2",
    "ipykernel==6.29.5",
    "ipython==8.30.0",
    "isoduration==20.11.0",
    "jedi==0.19.2",
    "jinja2==3.1.6",
    "joblib==1.4.2",
    "jsonpointer==3.0.0",
    "jsonschema==4.23.0",
    "jsonschema-specifications==2024.10.1",
    "jupyter-client==8.6.3",
    "jupyter-core==5.7.2",
    "jupyter-events==0.12.0",
    "jupyter-server==2.15.0",
    "jupyter-server-mathjax==0.2.6",
    "jupyter-server-terminals==0.5.3",
    "jupyterlab-pygments==0.3.0",
    "kiwisolver==1.4.8",
    "markupsafe==3.0.2",
    "matplotlib==3.10.0",
    "matplotlib-inline==0.1.6",
    "mistune==3.1.3",
    "mpmath==1.3.0",
    "mypy==1.15.0",
    "mypy-extensions==1.0.0",
    "nbclient==0.10.2",
    "nbdime==4.0.2",
    "nbformat==5.10.4",
    "nbqa==1.9.0",
    "nest-asyncio==1.6.0",
    "networkx==3.4.2",
    "nodeenv==1.9.1",
    "numpy==2.2.4",
    "opentelemetry-api==1.30.0",
    "overrides==7.7.0",
    "packaging==24.2",
    "pandas==2.2.3",
    "pandocfilters==1.5.0",
    "parso==0.8.4",
    "pexpect==4.8.0",
    "pillow==11.1.0",
    "pip==25.0",
    "pkgutil-resolve-name==1.3.10",
    "platformdirs==3.10.0",
    "pre-commit==4.2.0",
    "prometheus-client==0.21.1",
    "prompt-toolkit==3.0.43",
    "psutil==5.9.0",
    "ptyprocess==0.7.0",
    "pure-eval==0.2.2",
    "pycodestyle==2.13.0",
    "pycparser==2.22",
    "pygments==2.15.1",
    "pyobjc-core==11.0",
    "pyobjc-framework-cocoa==11.0",
    "pyparsing==3.2.0",
    "pysocks==1.7.1",
    "python-dateutil==2.9.0.post0",
    "python-json-logger==2.0.7",
    "pytz==2024.1",
    "pyyaml==6.0.2",
    "pyzmq==26.2.0",
    "referencing==0.36.2",
    "requests==2.32.3",
    "rfc3339-validator==0.1.4",
    "rfc3986-validator==0.1.1",
    "rpds-py==0.24.0",
    "ruff==0.9.1",
    "scikit-learn==1.6.1",
    "scipy==1.15.2",
    "seaborn==0.13.2",
    "send2trash==1.8.3",
    "setuptools==72.1.0",
    "six==1.16.0",
    "smmap==5.0.2",
    "sniffio==1.3.1",
    "soupsieve==2.5",
    "stack-data==0.2.0",
    "sympy==1.13.1",
    "terminado==0.18.1",
    "threadpoolctl==3.5.0",
    "tinycss2==1.4.0",
    "tokenize-rt==6.1.0",
    "tomli==2.2.1",
    "tornado==6.4.2",
    "traitlets==5.14.3",
    "types-python-dateutil==2.9.0.20241206",
    "typing-extensions==4.12.2",
    "typing-utils==0.1.0",
    "ukkonen==1.0.1",
    "uri-template==1.3.0",
    "urllib3==2.4.0",
    "virtualenv==20.30.0",
    "wcwidth==0.2.5",
    "webcolors==24.11.1",
    "webencodings==0.5.1",
    "websocket-client==1.8.0",
    "wheel==0.45.1",
    "wrapt==1.17.0",
    "zipp==3.21.0",
    "zstandard==0.23.0",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
    { index = "pytorch-cu124", marker = "sys_platform == 'linux'" },
]
torchvision = [
    { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
    { index = "pytorch-cu124", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true


[dependency-groups]
dev = [
    "mypy==1.15.0",
    "nbdime==4.0.2",
    "nbqa==1.9.0",
    "pre-commit==4.2.0",
    "ruff==0.9.1",
]
