name: Lint and Type Check

on:
  push:
    branches: ["dev/*"]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Sync environment from uv.lock
        run: uv sync

      - name: Run lint checks (ruff, mypy) on .py and .ipynb files"
        run: uv run make lint
